name: DCO
on:
  pull_request:
permissions: {}
jobs:
  dco:
    name: DCO
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-dco.yml@2383033519e5dd89bfd4e832659933a145e7acde # v0.2.0
