name: REUSE
on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
permissions: {}
jobs:
  reuse:
    name: REUSE
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-reuse.yml@2383033519e5dd89bfd4e832659933a145e7acde # v0.2.0
