name: scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
permissions: {}
jobs:
  scorecard:
    name: Scorecard
    permissions:
      contents: read
      id-token: write # signs published Scorecard results
    uses: openbunny/.github/.github/workflows/reusable-scorecard.yml@2383033519e5dd89bfd4e832659933a145e7acde # v0.2.0
    with:
      publish: true
